### ISSUE TITLE
queryStringParameters are discarded using lamed_http

### ISSUE THREAD

**Issue by dimtion** [lamedh-dev/aws-lambda-rust-runtime#21]
I created a simple Implicit Api Lambda that has `queryStringParameters` (`?x=12&y=13`) and I wanted to use `lamed_http` to handle the request. However all the `queryStringParameters` are discarded when using a `lamedh_http::Request` handler. Only the path part of the incoming URL is kept.

I believe the rebuilt URI from the Lambda event does not rebuild the the query part. 

Cloudformation:
```yaml
Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: test/
      Handler: bootstrap.my_handler
      Runtime: provided
      MemorySize: 512
      CodeUri: .
      Events:
        Test:
          Type: Api
          Properties:
            Path: "/test"
            Method: GET
            RequestParameters:
              - method.request.querystring.x
              - method.request.querystring.y
    Metadata:
      BuildMethod: makefile
```

Rust handler:
```rust
async fn request_handler(request: Request, context: Context) -> Result<impl IntoResponse, Error> {
    dbg!(&request);
    dbg!(&context);
    let query = request.uri().query().ok_or(ResponseError::InvalidQuery)?;  // Returns InvalidQuery since the `query` is empty
    dbg!(query);
    Ok(APIResponse::Ok)
}
```
Request received:
```
[src/main.rs:47] &request = Request {
    method: GET,
    uri: http://localhost:3000/test,
    version: HTTP/1.1,
    headers: {
        "accept": "*/*",
        "host": "localhost:3000",
        "user-agent": "curl/7.64.1",
        "x-forwarded-port": "3000",
        "x-forwarded-proto": "http",
    },
    body: Empty,
}
[src/main.rs:48] &context = Context {
    request_id: "90ca4c54-9933-4cd8-b796-734b8cd9da23",
    deadline: 3232776571703,
    invoked_function_arn: "",
    xray_trace_id: "",
    client_context: None,
    identity: None,
    env_config: Config {
        endpoint: "127.0.0.1:9001",
        function_name: "TestFunction",
        memory: 512,
        version: "$LATEST",
        log_stream: "$LATEST",
        log_group: "aws/lambda/TestFunction",
    },
}
REPORT RequestId: 90ca4c54-9933-4cd8-b796-734b8cd9da23  Init Duration: 0.17 ms  Duration: 77.13 ms      Billed Duration: 100 ms Memory Size: 512 MB     Max Memory Used: 512 MB
Lambda returned empty body!
Invalid lambda response received: Invalid API Gateway Response Keys: {'errorMessage', 'errorType'} in {'errorType': 'alloc::boxed::Box<dyn std::error::Error+core::marker::Send+core::marker::Sync>', 'errorMessage': 'InvalidQuery'}
```

The workaround I found was to use the simple `serde_json::Value` handler.

Thank you.
